### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by amybronzwaig**

### CODE REVIEW

**Comment by amybronzwaig** [comment]
The date of my assigned newspaper for the first deliverable is 1906-11-05, pages 1-3.

**Comment by whanley** [comment]
Thanks! But please move these files into the 1906-page-images-4 folder, then send a new pull request.

**Comment by whanley** [comment]
Thanks, Amy. One of these files is named and located properly: 1906-page-images-4/1906-11-05-p4.jpg. Please fix the names and locations of the other eight files, or delete those that are incorrect.

**Comment by whanley** [comment]
Great--thanks!

**Pull request merged**
