### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by stevensaxt**

### CODE REVIEW

**Comment by whanley** [comment]
Great, but these need to be uploaded into the 1907-page-images-4 folder.

**Comment by stevensaxt** [comment]
Hello,
I went to that folder and attempted to upload my images, but the upload
button took me to a page that had a lock on it and said  "Uploads are
disabled. File uploads need push access to this repository".

**Comment by stevensaxt** [comment]
Is there a workaround for this?

Thanks,
Steven Saxton

**Comment by huoyanzhizhou** [comment]
Did you went to the master repository (dig-eg-gaz/page-images)? You do not have access to that and please find the folder in your forked repository and upload them there.

**Comment by stevensaxt** [comment]
Ah, I see my confusion. It is fixed now. Thank you so much!

**Comment by whanley** [comment]
These files are still in the wrong place. You've added them to the page-images repository at the top level, and to dated folders _within_ the 1907-page-images-4 folder. Please delete these 40 files. Then add the twenty images to the 1907-page-images-4, and send a new pull request.

**Comment by stevensaxt** [comment]
So are the files in the proper place, just shouldn't be in the dated
folders? In other words, if I were to upload the images within the
1907-page-images-4 folder (where they are currently), but NOT in the
dated folders and instead as individual files, it would be correct?

Thanks and sorry for the confusion!

Steven Saxton

**Comment by stevensaxt** [comment]
Also, I haven't seen anything about the historical analysis group project,
is the draft that was scheduled to be due tonight still due? If so, what
does it involve?

Thanks again!

Steven Saxton

**Comment by whanley** [comment]
> if I were to upload the images within the
1907-page-images-4 folder (where they are currently), but NOT in the
dated folders and instead as individual files, it would be correct?

Exactly right.

> Also, I haven't seen anything about the historical analysis group project,
is the draft that was scheduled to be due tonight still due? If so, what
does it involve?

Check the email I just sent everyone, as well as the course home page on Canvas.

**Comment by stevensaxt** [comment]
Ah I see. Thank you so much again for your help!

Steven Saxton

**Pull request merged**
