### PR TITLE
1/14/1907-1/16/1907images

### PR DESCRIPTION
**Pull request by celinebenedico**
Celine Benedico
Thanks!

### CODE REVIEW

**Comment by celinebenedico** [comment]
Deliverable 7

**Comment by whanley** [comment]
Thanks, Celine--but these images have the wrong name. Instead of YYYY-MM-DDpage#.jpg, please use this format YYYY-MM-DD-p#.jpg

**Comment by whanley** [comment]
I'll just fix it for you.

**Comment by celinebenedico** [comment]
Thank you so much!! Sorry I did not do it earlier. Hope you’re staying safe and healthy! 

- Celine Benedico

**Pull request merged**
